object_src = [
  box3d-side.cpp
  'object/box3d.cpp',
  'object/color-profile.cpp',
  'object/object-set.cpp',
  'object/persp3d-reference.cpp',
  'object/persp3d.cpp',
  'object/sp-anchor.cpp',
  'object/sp-clippath.cpp',
  'object/sp-conn-end-pair.cpp',
  'object/sp-conn-end.cpp',
  'object/sp-defs.cpp',
  'object/sp-desc.cpp',
  'object/sp-dimensions.cpp',
  'object/sp-ellipse.cpp',
  'object/sp-factory.cpp',
  'object/sp-filter-reference.cpp',
  'object/sp-filter.cpp',
  'object/sp-flowdiv.cpp',
  'object/sp-flowregion.cpp',
  'object/sp-flowtext.cpp',
  'object/sp-font-face.cpp',
  'object/sp-font.cpp',
  'object/sp-glyph-kerning.cpp',
  'object/sp-glyph.cpp',
  'object/sp-gradient-reference.cpp',
  'object/sp-gradient.cpp',
  'object/sp-grid.cpp',
  'object/sp-guide.cpp',
  'object/sp-hatch-path.cpp',
  'object/sp-hatch.cpp',
  'object/sp-image.cpp',
  'object/sp-item-group.cpp',
  'object/sp-item-transform.cpp',
  'object/sp-item.cpp',
  'object/sp-line.cpp',
  'object/sp-linear-gradient.cpp',
  'object/sp-lpe-item.cpp',
  'object/sp-marker.cpp',
  'object/sp-mask.cpp',
  'object/sp-mesh-array.cpp',
  'object/sp-mesh-gradient.cpp',
  'object/sp-mesh-patch.cpp',
  'object/sp-mesh-row.cpp',
  'object/sp-metadata.cpp',
  'object/sp-missing-glyph.cpp',
  'object/sp-namedview.cpp',
  'object/sp-object-group.cpp',
  'object/sp-object.cpp',
  'object/sp-offset.cpp',
  'object/sp-paint-server.cpp',
  'object/sp-page.cpp',
  'object/sp-path.cpp',
  'object/sp-pattern.cpp',
  'object/sp-polygon.cpp',
  'object/sp-polyline.cpp',
  'object/sp-radial-gradient.cpp',
  'object/sp-rect.cpp',
  'object/sp-root.cpp',
  'object/sp-script.cpp',
  'object/sp-shape.cpp',
  'object/sp-shape-reference.cpp',
  'object/sp-solid-color.cpp',
  'object/sp-spiral.cpp',
  'object/sp-star.cpp',
  'object/sp-stop.cpp',
  'object/sp-string.cpp',
  'object/sp-style-elem.cpp',
  'object/sp-switch.cpp',
  'object/sp-symbol.cpp',
  'object/sp-tag-use-reference.cpp',
  'object/sp-tag-use.cpp',
  'object/sp-tag.cpp',
  'object/sp-text.cpp',
  'object/sp-title.cpp',
  'object/sp-tref-reference.cpp',
  'object/sp-tref.cpp',
  'object/sp-tspan.cpp',
  'object/sp-use-reference.cpp',
  'object/sp-use.cpp',
  'object/uri-references.cpp',
  'object/uri.cpp',
  'object/viewbox.cpp',

  # -------
  # Headers
  'object/box3d-side.h',
  'object/box3d.h',
  'object/color-profile.h',
  'object/object-set.h',
  'object/object-view.h',
  'object/persp3d-reference.h',
  'object/persp3d.h',
  'object/sp-anchor.h',
  'object/sp-clippath.h',
  'object/sp-conn-end-pair.h',
  'object/sp-conn-end.h',
  'object/sp-defs.h',
  'object/sp-desc.h',
  'object/sp-dimensions.h',
  'object/sp-ellipse.h',
  'object/sp-factory.h',
  'object/sp-filter-reference.h',
  'object/sp-filter-units.h',
  'object/sp-filter.h',
  'object/sp-flowdiv.h',
  'object/sp-flowregion.h',
  'object/sp-flowtext.h',
  'object/sp-font-face.h',
  'object/sp-font.h',
  'object/sp-glyph-kerning.h',
  'object/sp-glyph.h',
  'object/sp-gradient-reference.h',
  'object/sp-gradient-spread.h',
  'object/sp-gradient-units.h',
  'object/sp-gradient-vector.h',
  'object/sp-gradient.h',
  'object/sp-grid.h',
  'object/sp-guide.h',
  'object/sp-hatch-path.h',
  'object/sp-hatch.h',
  'object/sp-image.h',
  'object/sp-item-group.h',
  'object/sp-item-transform.h',
  'object/sp-item.h',
  'object/sp-line.h',
  'object/sp-linear-gradient.h',
  'object/sp-lpe-item.h',
  'object/sp-marker-loc.h',
  'object/sp-marker.h',
  'object/sp-mask.h',
  'object/sp-mesh-array.h',
  'object/sp-mesh-gradient.h',
  'object/sp-mesh-patch.h',
  'object/sp-mesh-row.h',
  'object/sp-metadata.h',
  'object/sp-missing-glyph.h',
  'object/sp-namedview.h',
  'object/sp-object-group.h',
  'object/sp-object-iterator.h',
  'object/sp-object.h',
  'object/sp-offset.h',
  'object/sp-paint-server-reference.h',
  'object/sp-paint-server.h',
  'object/sp-page.h',
  'object/sp-path.h',
  'object/sp-pattern.h',
  'object/sp-polygon.h',
  'object/sp-polyline.h',
  'object/sp-radial-gradient.h',
  'object/sp-rect.h',
  'object/sp-root.h',
  'object/sp-script.h',
  'object/sp-shape.h',
  'object/sp-shape-reference.h',
  'object/sp-solid-color.h',
  'object/sp-spiral.h',
  'object/sp-star.h',
  'object/sp-stop.h',
  'object/sp-string.h',
  'object/sp-style-elem.h',
  'object/sp-switch.h',
  'object/sp-symbol.h',
  'object/sp-tag.h',
  'object/sp-tag-use.h',
  'object/sp-tag-use-reference.h',
  'object/sp-text.h',
  'object/sp-textpath.h',
  'object/sp-title.h',
  'object/sp-tref-reference.h',
  'object/sp-tref.h',
  'object/sp-tspan.h',
  'object/sp-use-reference.h',
  'object/sp-use.h',
  'object/uri-references.h',
  'object/uri.h',
  'object/viewbox.h',
  'object/weakptr.h',
  'object/tags.h',
]

subdir('filters')
subdir('algorithms')

lib_inkscape_src += object_src