option('with_gnu_readline', description: 'Compile with GNU Readline support (shell mode)', value: true, type: 'boolean')
option('enable_lcms', description: 'Compile with LCMS support', value: true, type: 'boolean')
option('with_svg2', description: 'Compile with support for new SVG2 features', value: true, type: 'boolean')
option('with_lpetool', description: 'Compile with LPE Tool', value: false, type: 'boolean')
option('lpe_enable_test_effects', description: 'Compile with test experimental LPEs enabled', value: false, type: 'boolean')
option('with_profiling', description: 'Turn on profiling', value: false, type: 'boolean') # Set to true if compiler/linker should enable profiling
option('build_shared_libs', description: 'Compile libraries as shared and not static', value: true, type: 'boolean')
option('with_poppler', description: 'Compile with support of libpoppler', value: true, type: 'boolean')
option('with_capypdf', description: 'Compile with support of libcapypdf', value: true, type: 'boolean')
option('enable_poppler_cairo', description: 'Compile with support of libpoppler-cairo for rendering PDF preview (depends on with_poppler)', value: true, type: 'boolean')
option('with_image_magick', description: 'Compile with support of ImageMagick for raster extensions and image import resolution (requires ImageMagick 6; set to OFF if you prefer GraphicsMagick)', value: true, type: 'boolean')
option('with_graphics_magick', description: 'Compile with support of GraphicsMagick for raster extensions and image import resolution', value: true, type: 'boolean')
option('with_libcdr', description: 'Compile with support of libcdr for CorelDRAW Diagrams', value: true, type: 'boolean')
option('with_libvisio', description: 'Compile with support of libvisio for Microsoft Visio Diagrams', value: true, type: 'boolean')
option('with_libwpg', description: 'Compile with support of libwpg for WordPerfect Graphics', value: true, type: 'boolean')
option('with_libspelling', description: 'Compile with support of libspelling', value: true, type: 'boolean')
option('with_gsourceview', description: 'Compile with support of gsourceview (text syntax coloring)', value: true, type: 'boolean')
option('with_nls', description: 'Compile with Native Language Support (using gettext)', value: true, type: 'boolean')
option('with_jemalloc', description: 'Compile with JEMALLOC support', value: false, type: 'boolean')
option('with_asan', description: 'Compile with Clang\'s AddressSanitizer (for debugging purposes)', value: false, type: 'boolean')
option('with_internal_2geom', description: 'Prefer internal copy of lib2geom', value: false, type: 'boolean')
option('with_crossink', description: 'Cross-compiling with Crossroads', value: false, type: 'boolean')
option('with_fuzz', description: 'Compile for fuzzing purpose (use "make fuzz" only)', value: false, type: 'boolean')
option('with_manpage_compression', description: 'gzips manpages if gzip is available', value: true, type: 'boolean')
option('enable_binary_relocation', description: 'Enable relocatable binaries', value: false, type: 'boolean')
