filters_src = [
  'object/filters/sp-filter-primitive.cpp',
  'object/filters/blend.cpp',
  'object/filters/colormatrix.cpp',
  'object/filters/componenttransfer-funcnode.cpp',
  'object/filters/componenttransfer.cpp',
  'object/filters/composite.cpp',
  'object/filters/convolvematrix.cpp',
  'object/filters/diffuselighting.cpp',
  'object/filters/displacementmap.cpp',
  'object/filters/distantlight.cpp',
  'object/filters/dropshadow.cpp',
  'object/filters/flood.cpp',
  'object/filters/gaussian-blur.cpp',
  'object/filters/image.cpp',
  'object/filters/merge.cpp',
  'object/filters/mergenode.cpp',
  'object/filters/morphology.cpp',
  'object/filters/offset.cpp',
  'object/filters/pointlight.cpp',
  'object/filters/specularlighting.cpp',
  'object/filters/spotlight.cpp',
  'object/filters/slot-resolver.cpp',
  'object/filters/tile.cpp',
  'object/filters/turbulence.cpp',

  # -------
  # Headers
  'object/filters/sp-filter-primitive.h',
  'object/filters/blend.h',
  'object/filters/colormatrix.h',
  'object/filters/componenttransfer-funcnode.h',
  'object/filters/componenttransfer.h',
  'object/filters/composite.h',
  'object/filters/convolvematrix.h',
  'object/filters/diffuselighting.h',
  'object/filters/displacementmap.h',
  'object/filters/distantlight.h',
  'object/filters/dropshadow.h',
  'object/filters/flood.h',
  'object/filters/gaussian-blur.h',
  'object/filters/image.h',
  'object/filters/merge.h',
  'object/filters/mergenode.h',
  'object/filters/morphology.h',
  'object/filters/offset.h',
  'object/filters/pointlight.h',
  'object/filters/specularlighting.h',
  'object/filters/spotlight.h',
  'object/filters/slot-resolver.h',
  'object/filters/tile.h',
  'object/filters/turbulence.h'
]

object_src += filters_src