# SPDX-License-Identifier: GPL-2.0-or-later

trace_src = [
	'trace/cielab.cpp',
	'trace/filterset.cpp',
	'trace/imagemap.cpp',
	'trace/imagemap-gdk.cpp',
	'trace/quantize.cpp',
	'trace/siox.cpp',
	'trace/trace.cpp',

	'trace/potrace/inkscape-potrace.cpp',
	'trace/autotrace/inkscape-autotrace.cpp',
	'trace/depixelize/inkscape-depixelize.cpp',

	# -------
	# Headers
	'trace/cielab.h',
	'trace/filterset.h',
	'trace/imagemap-gdk.h',
	'trace/imagemap.h',
	'trace/pool.h',
	'trace/quantize.h',
	'trace/siox.h',
	'trace/trace.h',

	'trace/potrace/bitmap.h',
	'trace/potrace/inkscape-potrace.h',
	'trace/autotrace/inkscape-autotrace.h',
	'trace/depixelize/inkscape-depixelize.h'
]

lib_inkscape_src += trace_src

