util_src = [
	'util/action-accel.cpp',
    'util/document-fonts.cpp',
    'util/drawing-utils.cpp',
    'util/expression-evaluator.cpp',
    'util/font-collections.cpp',
    'util/format_size.cpp',
    'util/font-discovery.cpp',
    'util/font-tags.cpp',
    'util/funclog.cpp',
	'util/glyph-draw.cpp',
    'util/share.cpp',
    'util/object-renderer.cpp',
    'util/object-modified-tags.cpp',
    'util/paper.cpp',
    'util/parse-int-range.cpp',
    'util/preview.cpp',
    'util/source_date_epoch.cpp',
    'util/statics.cpp',
    'util/theme-utils.cpp',
    'util/recently-used-fonts.cpp',
    'util/pool.cpp',
    'util/treeify.cpp',
	'util/unicode.cpp',
    'util/units.cpp',
    'util/uri.cpp',
    'util/ziptool.cpp',

	# -------
	# Headers
	'util/action-accel.h',
	'util/cached_map.h',
	'util/cast.h',
	'util/const_char_ptr.h',
	'util/delete-with.h',
    'util/document-fonts.h',
    'util/drawing-utils.h',
    'util/enums.h',
    'util/expression-evaluator.h',
    'util/font-collections.h',
    'util/fixed_point.h',
    'util/font-discovery.h',
    'util/font-tags.h',
    'util/format.h',
    'util/format_size.h',
    'util/forward-pointer-iterator.h',
    'util/funclog.h',
	'util/glyph-draw.h',
    'util/hybrid-pointer.h',
    'util/longest-common-suffix.h',
    'util/object-renderer.h',
    'util/object-modified-tags.h',
    'util/optstr.h',
    'util/pages-skeleton.h',
    'util/paper.h',
    'util/parse-int-range.h',
    'util/pool.h',
    'util/preview.h',
    'util/recently-used-fonts.h',
    'util/reference.h',
    'util/scope_exit.h',
    'util/share.h',
    'util/signal-blocker.h',
    'util/source_date_epoch.h',
    'util/statics.h',
    'util/static-doc.h',
    'util/theme-utils.h',
    'util/treeify.h',
    'util/trim.h',
    'util/smart_ptr_keys.h',
	'util/unicode.h',
    'util/units.h',
    'util/uri.h',
    'util/variant-visitor.h',
    'util/value-utils.h',
    'util/ziptool.h',
    'util/numeric/converters.h',
]

util = shared_library('util', util_src)