libnrtype_src = [
	'libnrtype/font-factory.cpp',
	'libnrtype/font-instance.cpp',
	'libnrtype/font-lister.cpp',
	'libnrtype/Layout-TNG.cpp',
	'libnrtype/Layout-TNG-Compute.cpp',
	'libnrtype/Layout-TNG-Input.cpp',
	'libnrtype/Layout-TNG-OutIter.cpp',
	'libnrtype/Layout-TNG-Output.cpp',
	'libnrtype/Layout-TNG-Scanline-Makers.cpp',
	'libnrtype/OpenTypeUtil.cpp',
	'libnrtype/style-attachments.cpp',
	# -------
	# Headers
	'libnrtype/font-factory.h',
	'libnrtype/font-glyph.h',
	'libnrtype/font-instance.h',
	'libnrtype/font-lister.h',
	'libnrtype/Layout-TNG-Scanline-Maker.h',
	'libnrtype/Layout-TNG.h',
	'libnrtype/OpenTypeUtil.h',
	'libnrtype/style-attachments.h'
]

lib_inkscape_src += libnrtype_src