extensions_src = [
	'extension/db.cpp',
	'extension/dependency.cpp',
    'extension/processing-action.cpp',
	'extension/effect.cpp',
	'extension/execution-env.cpp',
	'extension/extension.cpp',
	'extension/init.cpp',
	'extension/input.cpp',
	'extension/output.cpp',
	'extension/patheffect.cpp',
	'extension/print.cpp',
	'extension/system.cpp',
	'extension/template.cpp',
	'extension/timer.cpp',
    'extension/loader.cpp',
	'extension/implementation/implementation.cpp',
	'extension/implementation/xslt.cpp',
	'extension/implementation/script.cpp',
	'extension/internal/bluredge.cpp',
	'extension/internal/cairo-ps-out.cpp',
	'extension/internal/cairo-render-context.cpp',
	'extension/internal/cairo-renderer.cpp',
	'extension/internal/cairo-renderer-pdf-out.cpp',
	'extension/internal/emf-inout.cpp',
	'extension/internal/emf-print.cpp',
	'extension/internal/gdkpixbuf-input.cpp',
	'extension/internal/gif.cpp',
	'extension/internal/gimpgrad.cpp',
	'extension/internal/grid.cpp',
	'extension/internal/image-resolution.cpp',
	'extension/internal/latex-pstricks.cpp',
	'extension/internal/latex-pstricks-out.cpp',
	'extension/internal/metafile-inout.cpp',
	'extension/internal/metafile-print.cpp',
	'extension/internal/odf.cpp',
	'extension/internal/latex-text-renderer.cpp',
	'extension/internal/png-output.cpp',
	'extension/internal/pov-out.cpp',
	'extension/internal/svg.cpp',
	'extension/internal/svgz.cpp',
	'extension/internal/template-base.cpp',
	'extension/internal/template-from-file.cpp',
	'extension/internal/template-other.cpp',
	'extension/internal/template-paper.cpp',
	'extension/internal/template-screen.cpp',
	'extension/internal/template-social.cpp',
	'extension/internal/template-video.cpp',
	'extension/internal/text_reassemble.c',
	'extension/internal/wmf-inout.cpp',
	'extension/internal/wmf-print.cpp',
	'extension/internal/filter/filter-all.cpp',
	'extension/internal/filter/filter-file.cpp',
	'extension/internal/filter/filter.cpp',
	'extension/prefdialog/prefdialog.cpp',
	'extension/prefdialog/parameter.cpp',
	'extension/prefdialog/parameter-bool.cpp',
	'extension/prefdialog/parameter-color.cpp',
	'extension/prefdialog/parameter-float.cpp',
	'extension/prefdialog/parameter-int.cpp',
	'extension/prefdialog/parameter-notebook.cpp',
	'extension/prefdialog/parameter-optiongroup.cpp',
	'extension/prefdialog/parameter-path.cpp',
	'extension/prefdialog/parameter-string.cpp',
	'extension/prefdialog/widget.cpp',
	'extension/prefdialog/widget-box.cpp',
	'extension/prefdialog/widget-image.cpp',
	'extension/prefdialog/widget-label.cpp',
	'extension/prefdialog/widget-separator.cpp',
	'extension/prefdialog/widget-spacer.cpp',
	'extension/# ------',
	'extension/# Header',
	'extension/db.h',
	'extension/dependency.h',
    'extension/    processing-action.h',
	'extension/effect.h',
	'extension/execution-env.h',
	'extension/extension.h',
	'extension/init.h',
	'extension/input.h',
	'extension/output.h',
	'extension/patheffect.h',
	'extension/print.h',
	'extension/system.h',
	'extension/template.h',
	'extension/timer.h',
    'extension/loader.h',
	'extension/implementation/implementation.h',
	'extension/implementation/script.h',
	'extension/implementation/xslt.h',
	'extension/internal/bluredge.h',
	'extension/internal/cairo-ps-out.h',
	'extension/internal/cairo-render-context.h',
	'extension/internal/cairo-renderer-pdf-out.h',
	'extension/internal/cairo-renderer.h',
	'extension/internal/clear-n_.h',
	'extension/internal/emf-inout.h',
	'extension/internal/emf-print.h',
	'extension/internal/filter/bevels.h',
	'extension/internal/filter/blurs.h',
	'extension/internal/filter/bumps.h',
	'extension/internal/filter/color.h',
	'extension/internal/filter/distort.h',
	'extension/internal/filter/filter.h',
	'extension/internal/filter/image.h',
	'extension/internal/filter/morphology.h',
	'extension/internal/filter/overlays.h',
	'extension/internal/filter/paint.h',
	'extension/internal/filter/protrusions.h',
	'extension/internal/filter/shadows.h',
	'extension/internal/filter/textures.h',
	'extension/internal/filter/transparency.h',
	'extension/internal/gdkpixbuf-input.h',
	'extension/internal/gif.h',
	'extension/internal/lib-gif.h',
	'extension/internal/gimpgrad.h',
	'extension/internal/grid.h',
	'extension/internal/image-resolution.h',
	'extension/internal/latex-pstricks-out.h',
	'extension/internal/latex-pstricks.h',
	'extension/internal/latex-text-renderer.h',
	'extension/internal/metafile-inout.h',
	'extension/internal/metafile-print.h',
	'extension/internal/odf.h',
	'extension/internal/pdfinput/enums.h',
	'extension/internal/png-output.h',
	'extension/internal/pov-out.h',
	'extension/internal/svg.h',
	'extension/internal/svgz.h',
	'extension/internal/template-base.h',
	'extension/internal/template-from-file.h',
	'extension/internal/template-other.h',
	'extension/internal/template-paper.h',
	'extension/internal/template-screen.h',
	'extension/internal/template-social.h',
	'extension/internal/template-video.h',
	'extension/internal/text_reassemble.h',
	'extension/internal/wmf-inout.h',
	'extension/internal/wmf-print.h',
	'extension/prefdialog/prefdialog.h',
	'extension/prefdialog/parameter.h',
	'extension/prefdialog/parameter-bool.h',
	'extension/prefdialog/parameter-color.h',
	'extension/prefdialog/parameter-float.h',
	'extension/prefdialog/parameter-int.h',
	'extension/prefdialog/parameter-notebook.h',
	'extension/prefdialog/parameter-optiongroup.h',
	'extension/prefdialog/parameter-path.h',
	'extension/prefdialog/parameter-string.h',
	'extension/prefdialog/widget.h',
	'extension/prefdialog/widget-box.h',
	'extension/prefdialog/widget-image.h',
	'extension/prefdialog/widget-label.h',
	'extension/prefdialog/widget-separator.h',
	'extension/prefdialog/widget-spacer.h',
]

lib_inkscape_src += extensions_src