ui_src = [
	'ui/builder-utils.cpp',
	'ui/clipboard.cpp',
	'ui/contextmenu.cpp',
	'ui/cursor-utils.cpp',
	'ui/dialog-events.cpp',
	'ui/dialog-run.cpp',
	'ui/draw-anchor.cpp',
	'ui/drag-and-drop.cpp',
	'ui/gridview-utils.cpp',
	'ui/icon-loader.cpp',
	'ui/interface.cpp',
	'ui/monitor.cpp',
	'ui/pack.cpp',
	'ui/popup-menu.cpp',
	'ui/shape-editor.cpp',
	'ui/shape-editor-knotholders.cpp',
	'ui/simple-pref-pusher.cpp',
	'ui/shortcuts.cpp',
	'ui/svg-renderer.cpp',
	'ui/syntax.cpp',
	'ui/themes.cpp',
	'ui/tool-factory.cpp',
	'ui/util.cpp',
	'ui/modifiers.cpp',
	'ui/cache/svg_preview_cache.cpp',
	'ui/desktop/document-check.cpp',
	'ui/desktop/menubar.cpp',
	'ui/desktop/menu-set-tooltips-shift-icons.cpp',
	'ui/knot/knot.cpp',
	'ui/knot/knot-holder.cpp',
	'ui/knot/knot-holder-entity.cpp',
	'ui/knot/knot-ptr.cpp',
	'ui/tool/control-point-selection.cpp',
	'ui/tool/control-point.cpp',
	'ui/tool/curve-drag-point.cpp',
	'ui/tool/modifier-tracker.cpp',
	'ui/tool/multi-path-manipulator.cpp',
	'ui/tool/node.cpp',
	'ui/tool/path-manipulator.cpp',
	'ui/tool/selectable-control-point.cpp',
	'ui/tool/transform-handle-set.cpp',
	'ui/toolbar/arc-toolbar.cpp',
	'ui/toolbar/box3d-toolbar.cpp',
	'ui/toolbar/calligraphy-toolbar.cpp',
	'ui/toolbar/connector-toolbar.cpp',
	'ui/toolbar/dropper-toolbar.cpp',
	'ui/toolbar/marker-toolbar.cpp',
	'ui/toolbar/eraser-toolbar.cpp',
	'ui/toolbar/gradient-toolbar.cpp',
	'ui/toolbar/lpe-toolbar.cpp',
	'ui/toolbar/measure-toolbar.cpp',
	'ui/toolbar/mesh-toolbar.cpp',
	'ui/toolbar/node-toolbar.cpp',
	'ui/toolbar/objectpicker-toolbar.cpp',
	'ui/toolbar/page-toolbar.cpp',
	'ui/toolbar/paintbucket-toolbar.cpp',
	'ui/toolbar/pencil-toolbar.cpp',
	'ui/toolbar/rect-toolbar.cpp',
	'ui/toolbar/select-toolbar.cpp',
	'ui/toolbar/booleans-toolbar.cpp',
	'ui/toolbar/spiral-toolbar.cpp',
	'ui/toolbar/spray-toolbar.cpp',
	'ui/toolbar/star-toolbar.cpp',
	'ui/toolbar/text-toolbar.cpp',
	'ui/toolbar/toolbar.cpp',
	'ui/toolbar/tweak-toolbar.cpp',
	'ui/toolbar/zoom-toolbar.cpp',
	'ui/toolbar/command-toolbar.cpp',
	'ui/toolbar/tool-toolbar.cpp',
	'ui/toolbar/snap-toolbar.cpp',
	'ui/toolbar/toolbars.cpp',
	'ui/tools/arc-tool.cpp',
	'ui/tools/box3d-tool.cpp',
	'ui/tools/calligraphic-tool.cpp',
	'ui/tools/connector-tool.cpp',
	'ui/tools/dropper-tool.cpp',
	'ui/tools/dynamic-base.cpp',
	'ui/tools/eraser-tool.cpp',
	'ui/tools/flood-tool.cpp',
	'ui/tools/freehand-base.cpp',
	'ui/tools/gradient-tool.cpp',
	'ui/tools/lpe-tool.cpp',
	'ui/tools/measure-tool.cpp',
	'ui/tools/mesh-tool.cpp',
	'ui/tools/node-tool.cpp',
	'ui/tools/object-picker-tool.cpp',
	'ui/tools/pages-tool.cpp',
	'ui/tools/pencil-tool.cpp',
	'ui/tools/pen-tool.cpp',
	'ui/tools/rect-tool.cpp',
	'ui/tools/marker-tool.cpp',
	'ui/tools/select-tool.cpp',
	'ui/tools/booleans-builder.cpp',
	'ui/tools/booleans-tool.cpp',
	'ui/tools/booleans-subitems.cpp',
	'ui/tools/shortcuts.cpp',
	'ui/tools/spiral-tool.cpp',
	'ui/tools/spray-tool.cpp',
	'ui/tools/star-tool.cpp',
	'ui/tools/text-tool.cpp',
	'ui/tools/tool-base.cpp',
	'ui/tools/tool-data.cpp',
	'ui/tools/tweak-tool.cpp',
	'ui/tools/zoom-tool.cpp',
	'ui/dialog/about.cpp',
	'ui/dialog/align-and-distribute.cpp',
	'ui/dialog/attrdialog.cpp',
	'ui/dialog/calligraphic-profile-rename.cpp',
	'ui/dialog/clonetiler.cpp',
	'ui/dialog/color-item.cpp',
	'ui/dialog/command-palette.cpp',
	'ui/dialog/attrdialog.cpp',
	'ui/dialog/choose-file.cpp',
	'ui/dialog/debug.cpp',
	'ui/dialog/choose-file-utils.cpp',
	'ui/dialog/dialog-base.cpp',
	'ui/dialog/dialog-container.cpp',
	'ui/dialog/dialog-data.cpp',
	'ui/dialog/dialog-manager.cpp',
	'ui/dialog/dialog-multipaned.cpp',
	'ui/dialog/dialog-notebook.cpp',
	'ui/dialog/dialog-window.cpp',
	'ui/dialog/document-properties.cpp',
	'ui/dialog/document-resources.cpp',
	'ui/dialog/export.cpp',
	'ui/dialog/export-batch.cpp',
	'ui/dialog/export-single.cpp',
	'ui/dialog/extensions-gallery.cpp',
	'ui/dialog/fill-and-stroke.cpp',
	'ui/dialog/filter-effects-dialog.cpp',
	'ui/dialog/find.cpp',
	'ui/dialog/font-collections-manager.cpp',
	'ui/dialog/font-substitution.cpp',
	'ui/dialog/global-palettes.cpp',
	'ui/dialog/glyphs.cpp',
	'ui/dialog/grid-arrange-tab.cpp',
	'ui/dialog/guides.cpp',
	'ui/dialog/icon-preview.cpp',
	'ui/dialog/inkscape-preferences.cpp',
	'ui/dialog/knot-properties.cpp',
	'ui/dialog/layer-properties.cpp',
	'ui/dialog/livepatheffect-editor.cpp',
	'ui/dialog/lpe-fillet-chamfer-properties.cpp',
	'ui/dialog/lpe-powerstroke-properties.cpp',
	'ui/dialog/measure-tool-settings.cpp',
	'ui/dialog/new-from-template.cpp',
	'ui/dialog/object-attributes.cpp',
	'ui/dialog/object-properties.cpp',
	'ui/dialog/objects.cpp',
	'ui/dialog/polar-arrange-tab.cpp',
	'ui/dialog/print.cpp',
	'ui/dialog/prototype.cpp',
	'ui/dialog/save-image.cpp',
	'ui/dialog/selectorsdialog.cpp',
	'ui/dialog/startup.cpp',
	'ui/dialog/styledialog.cpp',
	'ui/dialog/svg-fonts-dialog.cpp',
	'ui/dialog/swatches.cpp',
	'ui/dialog/symbols.cpp',
	'ui/dialog/paint-servers.cpp',
	'ui/dialog/text-edit.cpp',
	'ui/dialog/tile.cpp',
	'ui/dialog/tracedialog.cpp',
	'ui/dialog/transformation.cpp',
	'ui/dialog/undo-history.cpp',
	'ui/dialog/xml-tree.cpp',
	'ui/dialog/save-template-dialog.cpp',
	'ui/widget-vfuncs-class-init.cpp',
	'ui/widget/character-viewer.cpp',
	'ui/widget/iconrenderer.cpp',
	'ui/widget/ink-property-grid.cpp',
	'ui/widget/alignment-selector.cpp',
	'ui/widget/anchor-selector.cpp',
	'ui/widget/completion-popup.cpp',
	'ui/widget/canvas.cpp',
	'ui/widget/canvas/stores.cpp',
	'ui/widget/canvas/synchronizer.cpp',
	'ui/widget/canvas/util.cpp',
	'ui/widget/canvas/texture.cpp',
	'ui/widget/canvas/texturecache.cpp',
	'ui/widget/canvas/pixelstreamer.cpp',
	'ui/widget/canvas/updaters.cpp',
	'ui/widget/canvas/framecheck.cpp',
	'ui/widget/canvas/glgraphics.cpp',
	'ui/widget/canvas/cairographics.cpp',
	'ui/widget/canvas/graphics.cpp',
	'ui/widget/canvas-grid.cpp',
	'ui/widget/canvas-notice.cpp',
	'ui/widget/color-entry.cpp',
	'ui/widget/color-notebook.cpp',
	'ui/widget/color-page.cpp',
	'ui/widget/color-palette.cpp',
	'ui/widget/color-palette-preview.cpp',
	'ui/widget/color-picker-panel.cpp',
	'ui/widget/color-picker.cpp',
	'ui/widget/color-plate.cpp',
	'ui/widget/color-preview.cpp',
	'ui/widget/color-slider.cpp',
	'ui/widget/color-wheel-factory.cpp',
	'ui/widget/combo-box-entry-tool-item.cpp',
	'ui/widget/combo-tool-item.cpp',
	'ui/widget/custom-tooltip.cpp',
	'ui/widget/dash-selector.cpp',
	'ui/widget/desktop-widget.cpp',
	'ui/widget/document-templates.cpp',
	'ui/widget/drop-down-list.cpp',
	'ui/widget/entity-entry.cpp',
	'ui/widget/entry.cpp',
	'ui/widget/export-lists.cpp',
	'ui/widget/export-preview.cpp',
	'ui/widget/filter-effect-chooser.cpp',
	'ui/widget/fill-style.cpp',
	'ui/widget/font-button.cpp',
	'ui/widget/font-collection-selector.cpp',
	'ui/widget/font-list.cpp',
	'ui/widget/font-selector.cpp',
	'ui/widget/font-variants.cpp',
	'ui/widget/font-variations.cpp',
	'ui/widget/frame.cpp',
	'ui/widget/generic/bin.cpp',
	'ui/widget/generic/css-name-class-init.cpp',
	'ui/widget/generic/dual-spin-scale.cpp',
	'ui/widget/generic/popover-bin.cpp',
	'ui/widget/generic/popover-menu.cpp',
	'ui/widget/generic/reorderable-stack.cpp',
	'ui/widget/generic/scale-bar.cpp',
	'ui/widget/generic/simple-grid.cpp',
	'ui/widget/generic/snapshot-widget.cpp',
	'ui/widget/generic/spin-button.cpp',
	'ui/widget/generic/tab-strip.cpp',
	'ui/widget/gradient-image.cpp',
	'ui/widget/gradient-editor.cpp',
	'ui/widget/gradient-selector.cpp',
	'ui/widget/gradient-vector-selector.cpp',
	'ui/widget/gradient-with-stops.cpp',
	'ui/widget/icon-combobox.cpp',
	'ui/widget/handle-preview.cpp',
	'ui/widget/image-properties.cpp',
	'ui/widget/imagetoggler.cpp',
	'ui/widget/ink-color-wheel.cpp',
	'ui/widget/ink-ruler.cpp',
	'ui/widget/labelled.cpp',
	'ui/widget/layer-selector.cpp',
	'ui/widget/licensor.cpp',
	'ui/widget/memory.cpp',
	'ui/widget/messages.cpp',
	'ui/widget/mesh-editor.cpp',
	'ui/widget/notebook-page.cpp',
	'ui/widget/object-composite-settings.cpp',
	'ui/widget/objects-dialog-cells.cpp',
	'ui/widget/oklab-color-wheel.cpp',
	'ui/widget/optglarea.cpp',
	'ui/widget/page-properties.cpp',
	'ui/widget/page-size-preview.cpp',
	'ui/widget/page-selector.cpp',
	'ui/widget/paint-attribute.cpp',
	'ui/widget/paint-enums.cpp',
	'ui/widget/paint-inherited.cpp',
	'ui/widget/paint-selector.cpp',
	'ui/widget/paint-switch.cpp',
	'ui/widget/pattern-editor.cpp',
	'ui/widget/point.cpp',
	'ui/widget/preferences-widget.cpp',
	'ui/widget/random.cpp',
	'ui/widget/registered-widget.cpp',
	'ui/widget/registry.cpp',
	'ui/widget/rendering-options.cpp',
	'ui/widget/resizing-separator.cpp',
	'ui/widget/rotateable.cpp',
	'ui/widget/scalar-unit.cpp',
	'ui/widget/scalar.cpp',
	'ui/widget/scroll-utils.cpp',
	'ui/widget/selected-style.cpp',
	'ui/widget/shapeicon.cpp',
	'ui/widget/spinbutton.cpp',
	'ui/widget/stack.cpp',
	'ui/widget/status-bar.cpp',
	'ui/widget/stroke-style.cpp',
	'ui/widget/stroke-options.cpp',
	'ui/widget/style/marker-combo-box.cpp',
	'ui/widget/style-subject.cpp',
	'ui/widget/style-swatch.cpp',
	'ui/widget/swatch-editor.cpp',
	'ui/widget/swatch-selector.cpp',
	'ui/widget/tabs-widget.cpp',
	'ui/widget/template-list.cpp',
	'ui/widget/text.cpp',
	'ui/widget/textpath-popover.cpp',
	'ui/widget/unit-menu.cpp',
	'ui/widget/unit-tracker.cpp',
	'ui/widget/xml-treeview.cpp',
	'ui/widget/property-utils.cpp',
	'ui/widget/recolor-art.cpp',
	'ui/widget/multi-marker-color-plate.cpp',
	'ui/widget/recolor-art-manager.cpp',
	'ui/view/svg-view-widget.cpp',
	# -------
	# Headers
	'ui/builder-utils.h',
	'ui/clipboard.h',
	'ui/contextmenu.h',
	'ui/containerize.h',
	'ui/controller.h',
	'ui/cursor-utils.h',
	'ui/control-types.h',
	'ui/defocus-target.h',
	'ui/dialog-events.h',
	'ui/dialog-run.h',
	'ui/drag-and-drop.h',
	'ui/draw-anchor.h',
	'ui/error-reporter.h',
	'ui/filtered-store.h',
	'ui/gridview-utils.h',
	'ui/icon-names.h',
	'ui/icon-loader.h',
	'ui/interface.h',
	'ui/monitor.h',
	'ui/pack.h',
	'ui/popup-menu.h',
	'ui/shape-editor.h',
	'ui/shape-editor-knotholders.h',
	'ui/simple-pref-pusher.h',
	'ui/shortcuts.h',
	'ui/svg-renderer.h',
	'ui/syntax.h',
	'ui/themes.h',
	'ui/tool-factory.h',
	'ui/util.h',
	'ui/modifiers.h',
	'ui/cache/svg_preview_cache.h',
	'ui/desktop/document-check.h',
	'ui/desktop/menubar.h',
	'ui/desktop/menu-set-tooltips-shift-icons.h',
	'ui/dialog/about.h',
	'ui/dialog/align-and-distribute.h',
	'ui/dialog/arrange-tab.h',
	'ui/dialog/calligraphic-profile-rename.h',
	'ui/dialog/choose-file.h',
	'ui/dialog/choose-file-utils.h',
	'ui/dialog/clonetiler.h',
	'ui/dialog/color-item.h',
	'ui/dialog/command-palette.h',
	'ui/dialog/attrdialog.h',
	'ui/dialog/debug.h',
	'ui/dialog/dialog-base.h',
	'ui/dialog/dialog-container.h',
	'ui/dialog/dialog-data.h',
	'ui/dialog/dialog-manager.h',
	'ui/dialog/dialog-multipaned.h',
	'ui/dialog/dialog-notebook.h',
	'ui/dialog/dialog-window.h',
	'ui/dialog/document-properties.h',
	'ui/dialog/document-resources.h',
	'ui/dialog/export.h',
	'ui/dialog/export-batch.h',
	'ui/dialog/export-single.h',
	'ui/dialog/extensions-gallery.h',
	'ui/dialog/fill-and-stroke.h',
	'ui/dialog/filter-effects-dialog.h',
	'ui/dialog/find.h',
	'ui/dialog/font-collections-manager.h',
	'ui/dialog/font-substitution.h',
	'ui/dialog/global-palettes.h',
	'ui/dialog/glyphs.h',
	'ui/dialog/grid-arrange-tab.h',
	'ui/dialog/guides.h',
	'ui/dialog/icon-preview.h',
	'ui/dialog/inkscape-preferences.h',
	'ui/dialog/knot-properties.h',
	'ui/dialog/layer-properties.h',
	'ui/dialog/livepatheffect-editor.h',
	'ui/dialog/lpe-fillet-chamfer-properties.h',
	'ui/dialog/lpe-powerstroke-properties.h',
	'ui/dialog/measure-tool-settings.h',
	'ui/dialog/new-from-template.h',
	'ui/dialog/object-attributes.h',
	'ui/dialog/object-properties.h',
	'ui/dialog/objects.h',
	'ui/dialog/polar-arrange-tab.h',
	'ui/dialog/print.h',
	'ui/dialog/prototype.h',
	'ui/dialog/save-image.h',
	'ui/dialog/selectorsdialog.h',
	'ui/dialog/startup.h',
	'ui/dialog/styledialog.h',
	'ui/dialog/svg-fonts-dialog.h',
	'ui/dialog/swatches.h',
	'ui/dialog/symbols.h',
	'ui/dialog/paint-servers.h',
	'ui/dialog/text-edit.h',
	'ui/dialog/tile.h',
	'ui/dialog/tracedialog.h',
	'ui/dialog/transformation.h',
	'ui/dialog/undo-history.h',
	'ui/dialog/xml-tree.h',
	'ui/dialog/save-template-dialog.h',
	'ui/knot/knot.h',
	'ui/knot/knot-enums.h',
	'ui/knot/knot-holder.h',
	'ui/knot/knot-holder-entity.h',
	'ui/knot/knot-ptr.h',
	'ui/tool/commit-events.h',
	'ui/tool/control-point-selection.h',
	'ui/tool/control-point.h',
	'ui/tool/curve-drag-point.h',
	'ui/tool/manipulator.h',
	'ui/tool/modifier-tracker.h',
	'ui/tool/multi-path-manipulator.h',
	'ui/tool/node-types.h',
	'ui/tool/node.h',
	'ui/tool/path-manipulator.h',
	'ui/tool/selectable-control-point.h',
	'ui/tool/shape-record.h',
	'ui/tool/transform-handle-set.h',
	'ui/toolbar/arc-toolbar.h',
	'ui/toolbar/box3d-toolbar.h',
	'ui/toolbar/calligraphy-toolbar.h',
	'ui/toolbar/connector-toolbar.h',
	'ui/toolbar/dropper-toolbar.h',
	'ui/toolbar/marker-toolbar.h',
	'ui/toolbar/eraser-toolbar.h',
	'ui/toolbar/gradient-toolbar.h',
	'ui/toolbar/lpe-toolbar.h',
	'ui/toolbar/measure-toolbar.h',
	'ui/toolbar/mesh-toolbar.h',
	'ui/toolbar/node-toolbar.h',
	'ui/toolbar/objectpicker-toolbar.h',
	'ui/toolbar/page-toolbar.h',
	'ui/toolbar/paintbucket-toolbar.h',
	'ui/toolbar/pencil-toolbar.h',
	'ui/toolbar/rect-toolbar.h',
	'ui/toolbar/select-toolbar.h',
	'ui/toolbar/booleans-toolbar.h',
	'ui/toolbar/spiral-toolbar.h',
	'ui/toolbar/spray-toolbar.h',
	'ui/toolbar/star-toolbar.h',
	'ui/toolbar/text-toolbar.h',
	'ui/toolbar/toolbar.h',
	'ui/toolbar/tweak-toolbar.h',
	'ui/toolbar/zoom-toolbar.h',
	'ui/toolbar/toolbar-constants.h',
	'ui/toolbar/toolbars.h',
	'ui/toolbar/command-toolbar.h',
	'ui/toolbar/tool-toolbar.h',
	'ui/toolbar/snap-toolbar.h',
	'ui/tools/arc-tool.h',
	'ui/tools/box3d-tool.h',
	'ui/tools/calligraphic-tool.h',
	'ui/tools/connector-tool.h',
	'ui/tools/dropper-tool.h',
	'ui/tools/dynamic-base.h',
	'ui/tools/eraser-tool.h',
	'ui/tools/flood-tool.h',
	'ui/tools/freehand-base.h',
	'ui/tools/gradient-tool.h',
	'ui/tools/lpe-tool.h',
	'ui/tools/measure-tool.h',
	'ui/tools/mesh-tool.h',
	'ui/tools/node-tool.h',
	'ui/tools/object-picker-tool.h',
	'ui/tools/pages-tool.h',
	'ui/tools/pen-tool.h',
	'ui/tools/pencil-tool.h',
	'ui/tools/rect-tool.h',
	'ui/tools/marker-tool.h',
	'ui/tools/select-tool.h',
	'ui/tools/booleans-builder.h',
	'ui/tools/booleans-tool.h',
	'ui/tools/booleans-subitems.h',
	'ui/tools/shortcuts.h',
	'ui/tools/spiral-tool.h',
	'ui/tools/spray-tool.h',
	'ui/tools/star-tool.h',
	'ui/tools/text-tool.h',
	'ui/tools/tool-base.h',
	'ui/tools/tool-data.h',
	'ui/tools/tweak-tool.h',
	'ui/tools/zoom-tool.h',
	'ui/widget-vfuncs-class-init.h',
	'ui/widget/iconrenderer.h',
	'ui/widget/ink-property-grid.h',
	'ui/widget/alignment-selector.h',
	'ui/widget/anchor-selector.h',
	'ui/widget/attr-widget.h',
	'ui/widget/canvas.h',
	'ui/widget/canvas/fragment.h',
	'ui/widget/canvas/prefs.h',
	'ui/widget/canvas/stores.h',
	'ui/widget/canvas/synchronizer.h',
	'ui/widget/canvas/util.h',
	'ui/widget/canvas/texture.h',
	'ui/widget/canvas/texturecache.h',
	'ui/widget/canvas/graphics.h',
	'ui/widget/canvas/pixelstreamer.h',
	'ui/widget/canvas/updaters.h',
	'ui/widget/canvas/framecheck.h',
	'ui/widget/canvas/glgraphics.h',
	'ui/widget/canvas/cairographics.h',
	'ui/widget/canvas-grid.h',
	'ui/widget/canvas-notice.h',
	'ui/widget/character-viewer.h',
	'ui/widget/completion-popup.h',
	'ui/widget/color-entry.h',
	'ui/widget/color-notebook.h',
	'ui/widget/color-page.h',
	'ui/widget/color-palette.h',
	'ui/widget/color-palette-preview.h',
	'ui/widget/color-picker.h',
	'ui/widget/color-picker-panel.h',
	'ui/widget/color-plate.h',
	'ui/widget/color-preview.h',
	'ui/widget/color-slider.h',
	'ui/widget/color-wheel.h',
	'ui/widget/color-wheel-factory.h',
	'ui/widget/combo-enums.h',
	'ui/widget/combo-box-entry-tool-item.h',
	'ui/widget/combo-tool-item.h',
	'ui/widget/custom-tooltip.h',
	'ui/widget/dash-selector.h',
	'ui/widget/desktop-widget.h',
	'ui/widget/drop-down-list.h',
	'ui/widget/document-templates.h',
	'ui/widget/edit-operation.h',
	'ui/widget/entity-entry.h',
	'ui/widget/entry.h',
	'ui/widget/events/canvas-event.h',
	'ui/widget/events/debug.h',
	'ui/widget/events/enums.h',
	'ui/widget/export-lists.h',
	'ui/widget/export-preview.h',
	'ui/widget/fill-style.h',
	'ui/widget/filter-effect-chooser.h',
	'ui/widget/font-button.h',
	'ui/widget/font-collection-selector.h',
	'ui/widget/font-list.h',
	'ui/widget/font-selector.h',
	'ui/widget/font-variants.h',
	'ui/widget/font-variations.h',
	'ui/widget/frame.h',
	'ui/widget/generic/bin.h',
	'ui/widget/generic/css-name-class-init.h',
	'ui/widget/generic/dual-spin-scale.h',
	'ui/widget/generic/popover-bin.h',
	'ui/widget/generic/popover-menu.h',
	'ui/widget/generic/reorderable-stack.h',
	'ui/widget/generic/scale-bar.h',
	'ui/widget/generic/simple-grid.h',
	'ui/widget/generic/snapshot-widget.h',
	'ui/widget/generic/spin-button.h',
	'ui/widget/generic/tab-strip.h',
	'ui/widget/gradient-image.h',
	'ui/widget/gradient-editor.h',
	'ui/widget/gradient-selector.h',
	'ui/widget/gradient-vector-selector.h',
	'ui/widget/gradient-with-stops.h',
	'ui/widget/icon-combobox.h',
	'ui/widget/handle-preview.h',
	'ui/widget/image-properties.h',
	'ui/widget/imagetoggler.h',
	'ui/widget/ink-color-wheel.h',
	'ui/widget/ink-ruler.h',
	'ui/widget/labelled.h',
	'ui/widget/layer-selector.h',
	'ui/widget/licensor.h',
	'ui/widget/memory.h',
	'ui/widget/messages.h',
	'ui/widget/mesh-editor.h',
	'ui/widget/notebook-page.h',
	'ui/widget/object-composite-settings.h',
	'ui/widget/objects-dialog-cells.h',
	'ui/widget/oklab-color-wheel.h',
	'ui/widget/optglarea.h',
	'ui/widget/page-selector.h',
	'ui/widget/paint-attribute.h',
	'ui/widget/paint-inherited.h',
	'ui/widget/paint-enums.h',
	'ui/widget/paint-selector.h',
	'ui/widget/paint-switch.h',
	'ui/widget/palette_t.h',
	'ui/widget/pattern-editor.h',
	'ui/widget/point.h',
	'ui/widget/preferences-widget.h',
	'ui/widget/random.h',
	'ui/widget/registered-enums.h',
	'ui/widget/registered-widget.h',
	'ui/widget/registry.h',
	'ui/widget/rendering-options.h',
	'ui/widget/resizing-separator.h',
	'ui/widget/rotateable.h',
	'ui/widget/scalar-unit.h',
	'ui/widget/scalar.h',
	'ui/widget/scroll-utils.h',
	'ui/widget/selected-style.h',
	'ui/widget/shapeicon.h',
	'ui/widget/size-reporter.h',
	'ui/widget/spinbutton.h',
	'ui/widget/stack.h',
	'ui/widget/status-bar.h',
	'ui/widget/stroke-style.h',
	'ui/widget/stroke-options.h',
	'ui/widget/style/marker-combo-box.h',
	'ui/widget/style-subject.h',
	'ui/widget/style-swatch.h',
	'ui/widget/swatch-editor.h',
	'ui/widget/swatch-selector.h',
	'ui/widget/tabs-widget.h',
	'ui/widget/template-list.h',
	'ui/widget/text.h',
	'ui/widget/textpath-popover.h',
	'ui/widget/unit-menu.h',
	'ui/widget/unit-tracker.h',
	'ui/widget/xml-treeview.h',
	'ui/widget/property-utils.h',
	'ui/widget/recolor-art.h',
	'ui/widget/multi-marker-color-plate.h',
	'ui/widget/recolor-art-manager.h',
	'ui/view/svg-view-widget.h'
]

ui_spellcheck_src = [
	'ui/dialog/spellcheck.cpp',
	'ui/dialog/spellcheck.h',
	'ui/libspelling-wrapper.h'
]

lib_inkscape_src += ui_src
lib_inkscape_src += ui_spellcheck_src