algorithms_src = [
  'object/algorithms/graphlayout.cpp',
  'object/algorithms/removeoverlap.cpp',
  'object/algorithms/unclump.cpp',

  # -------
  # Headers
  'object/algorithms/bboxsort.h
  'object/algorithms/graphlayout.h
  'object/algorithms/removeoverlap.h
  'object/algorithms/unclump.h
]

object_src += algorithms_src