colors_src = [
	'colors/cms/system.cpp',   # Needs preferences
	'colors/document-cms.cpp', # Links to sp-object tree
	'colors/dragndrop.cpp',    # Uses xml-color
	'colors/color-set.cpp',    # Uses unnlinkable sigc+
	'colors/xml-color.cpp',    # sp-document and document-cms
	'colors/cms/profile.h',
	'colors/document-cms.h',
	'colors/dragndrop.h',
	'colors/color-set.h',
	'colors/xml-color.h'
]

colors_unit_src = [
	'colors/cms/profile.cpp',
	'colors/cms/transform.cpp',
	'colors/cms/transform-color.cpp',
	'colors/cms/transform-cairo.cpp',
	'colors/color.cpp',
	'colors/manager.cpp',
	'colors/parser.cpp',
	'colors/printer.cpp',
	'colors/spaces/base.cpp',
	'colors/spaces/cms.cpp',
	'colors/spaces/cmyk.cpp',
	'colors/spaces/components.cpp',
	'colors/spaces/gamut.cpp',
	'colors/spaces/gray.cpp',
	'colors/spaces/hsl.cpp',
	'colors/spaces/hsluv.cpp',
	'colors/spaces/hsv.cpp',
	'colors/spaces/lab.cpp',
	'colors/spaces/lch.cpp',
	'colors/spaces/linear-rgb.cpp',
	'colors/spaces/luv.cpp',
	'colors/spaces/ok-color.cpp',
	'colors/spaces/okhsl.cpp',
	'colors/spaces/okhsv.cpp',
	'colors/spaces/oklab.cpp',
	'colors/spaces/oklch.cpp',
	'colors/spaces/named.cpp',
	'colors/spaces/rgb.cpp',
	'colors/spaces/xyz.cpp',
	'colors/utils.cpp',

	# -------
	# Headers
	'colors/cms/system.h',
	'colors/cms/transform.h',
	'colors/cms/transform-color.h',
	'colors/cms/transform-cairo.h',
	'colors/color.h',
	'colors/manager.h',
	'colors/parser.h',
	'colors/printer.h',
	'colors/spaces/base.h',
	'colors/spaces/cms.h',
	'colors/spaces/cmyk.h',
	'colors/spaces/components.h',
	'colors/spaces/enum.h',
	'colors/spaces/gamut.h',
	'colors/spaces/gray.h',
	'colors/spaces/hsl.h',
	'colors/spaces/hsluv.h',
	'colors/spaces/hsv.h',
	'colors/spaces/lab.h',
	'colors/spaces/lch.h',
	'colors/spaces/linear-rgb.h',
	'colors/spaces/luv.h',
	'colors/spaces/ok-color.h',
	'colors/spaces/okhsl.h',
	'colors/spaces/okhsv.h',
	'colors/spaces/oklab.h',
	'colors/spaces/oklch.h',
	'colors/spaces/named.h',
	'colors/spaces/rgb.h',
	'colors/spaces/xyz.h',
	'colors/utils.h'
]

lib_inkscape_src += colors_src
lib_inkscape_src += colors_unit_src