display_src = [
    'display/cairo-utils.cpp',
    'display/curve.cpp',
    'display/dispatch-pool.cpp',
    'display/drawing-context.cpp',
    'display/drawing-group.cpp',
    'display/drawing-image.cpp',
    'display/drawing-item.cpp',
    'display/drawing-paintserver.cpp',
    'display/drawing-pattern.cpp',
    'display/drawing-shape.cpp',
    'display/drawing-surface.cpp',
    'display/drawing-text.cpp',
    'display/drawing.cpp',
    'display/nr-3dutils.cpp',
    'display/nr-filter-blend.cpp',
    'display/nr-filter-colormatrix.cpp',
    'display/nr-filter-component-transfer.cpp',
    'display/nr-filter-composite.cpp',
    'display/nr-filter-convolve-matrix.cpp',
    'display/nr-filter-diffuselighting.cpp',
    'display/nr-filter-displacement-map.cpp',
    'display/nr-filter-dropshadow.cpp',
    'display/nr-filter-flood.cpp',
    'display/nr-filter-gaussian.cpp',
    'display/nr-filter-image.cpp',
    'display/nr-filter-merge.cpp',
    'display/nr-filter-morphology.cpp',
    'display/nr-filter-offset.cpp',
    'display/nr-filter-primitive.cpp',
    # nr-filter-skeleton.cpp
    'display/nr-filter-slot.cpp',
    'display/nr-filter-specularlighting.cpp',
    'display/nr-filter-tile.cpp',
    'display/nr-filter-turbulence.cpp',
    'display/nr-filter-units.cpp',
    'display/nr-filter.cpp',
    'display/nr-light.cpp',
    'display/nr-style.cpp',
    'display/nr-svgfonts.cpp',
    'display/threading.cpp',
    'display/translucency-group.cpp',
    'display/control/canvas-temporary-item-list.cpp',
    'display/control/canvas-temporary-item.cpp',
    'display/control/ctrl-handle-manager.cpp',
    'display/control/ctrl-handle-rendering.cpp',
    'display/control/ctrl-handle-styling.cpp',
    'display/control/snap-indicator.cpp',
    'display/control/canvas-item.cpp',
    'display/control/canvas-item-bpath.cpp',
    'display/control/canvas-item-catchall.cpp',
    'display/control/canvas-item-context.cpp',
    'display/control/canvas-item-ctrl.cpp',
    'display/control/canvas-item-curve.cpp',
    'display/control/canvas-item-drawing.cpp',
    'display/control/canvas-item-grid.cpp',
    'display/control/canvas-item-group.cpp',
    'display/control/canvas-item-guideline.cpp',
    'display/control/canvas-item-quad.cpp',
    'display/control/canvas-item-rect.cpp',
    'display/control/canvas-item-text.cpp',
    'display/control/canvas-page.cpp',
    # -------
    # Headers
    'display/cairo-templates.h',
    'display/cairo-utils.h',
    'display/curve.h',
    'display/dispatch-pool.h',
    'display/drawing-context.h',
    'display/drawing-group.h',
    'display/drawing-image.h',
    'display/drawing-item.h',
    'display/drawing-item-ptr.h',
    'display/drawing-paintserver.h',
    'display/drawing-pattern.h',
    'display/drawing-shape.h',
    'display/drawing-surface.h',
    'display/drawing-text.h',
    'display/drawing.h',
    'display/initlock.h',
    'display/nr-3dutils.h',
    'display/nr-filter-blend.h',
    'display/nr-filter-colormatrix.h',
    'display/nr-filter-component-transfer.h',
    'display/nr-filter-composite.h',
    'display/nr-filter-convolve-matrix.h',
    'display/nr-filter-diffuselighting.h',
    'display/nr-filter-displacement-map.h',
    'display/nr-filter-dropshadow.h',
    'display/nr-filter-flood.h',
    'display/nr-filter-gaussian.h',
    'display/nr-filter-image.h',
    'display/nr-filter-merge.h',
    'display/nr-filter-morphology.h',
    'display/nr-filter-offset.h',
    'display/nr-filter-primitive.h',
    'display/nr-filter-skeleton.h',
    'display/nr-filter-slot.h',
    'display/nr-filter-specularlighting.h',
    'display/nr-filter-tile.h',
    'display/nr-filter-turbulence.h',
    'display/nr-filter-types.h',
    'display/nr-filter-units.h',
    'display/nr-filter-utils.h',
    'display/nr-filter.h',
    'display/nr-light-types.h',
    'display/nr-light.h',
    'display/nr-style.h',
    'display/nr-svgfonts.h',
    'display/rendermode.h',
    'display/tags.h',
    'display/threading.h',
    'display/translucency-group.h',
    'display/control/canvas-temporary-item-list.h',
    'display/control/canvas-temporary-item.h',
    'display/control/ctrl-handle-manager.h',
    'display/control/ctrl-handle-rendering.h',
    'display/control/ctrl-handle-styling.h',
    'display/control/snap-indicator.h',
    'display/control/canvas-item.h',
    'display/control/canvas-item-bpath.h',
    'display/control/canvas-item-buffer.h',
    'display/control/canvas-item-catchall.h',
    'display/control/canvas-item-context.h',
    'display/control/canvas-item-ctrl.h',
    'display/control/canvas-item-curve.h',
    'display/control/canvas-item-drawing.h',
    'display/control/canvas-item-enums.h',
    'display/control/canvas-item-grid.h',
    'display/control/canvas-item-group.h',
    'display/control/canvas-item-guideline.h',
    'display/control/canvas-item-ptr.h',
    'display/control/canvas-item-quad.h',
    'display/control/canvas-item-rect.h',
    'display/control/canvas-item-text.h',
    'display/control/canvas-page.h'
]

lib_inkscape_src += display_src