debug_src = [
	'debug/console-output-undo-observer.cpp',
	'debug/demangle.cpp',
	'debug/heap.cpp',
	'debug/logger.cpp',
	'debug/sysv-heap.cpp',
	'debug/timestamp.cpp',
	# ------
	# Header
	'debug/console-output-undo-observer.h',
	'debug/demangle.h',
	'debug/event-tracker.h',
	'debug/event.h',
	'debug/gc-heap.h',
	'debug/heap.h',
	'debug/logger.h',
	'debug/simple-event.h',
	'debug/sysv-heap.h',
	'debug/timestamp.h'
]

lib_inkscape_src += debug_src