xml_src = [
	'xml/composite-node-observer.cpp',
	'xml/croco-node-iface.cpp',
	'xml/event.cpp',
	'xml/log-builder.cpp',
	'xml/node-fns.cpp',
	'xml/node.cpp',
	'xml/node-iterators.cpp',
	'xml/quote.cpp',
	'xml/repr.cpp',
	'xml/repr-css.cpp',
	'xml/repr-io.cpp',
	'xml/repr-sorting.cpp',
	'xml/repr-util.cpp',
	'xml/simple-document.cpp',
	'xml/simple-node.cpp',
	'xml/subtree.cpp',
	'xml/helper-observer.cpp',
	'xml/rebase-hrefs.cpp',
	'xml/href-attribute-helper.cpp',


	# -------
	# Headers
	'xml/attribute-record.h',
	'xml/comment-node.h',
	'xml/composite-node-observer.h',
	'xml/croco-node-iface.h',
	'xml/document.h',
	'xml/element-node.h',
	'xml/event-fns.h',
	'xml/event.h',
	'xml/helper-observer.h',
	'xml/invalid-operation-exception.h',
	'xml/log-builder.h',
	'xml/node-fns.h',
	'xml/node-iterators.h',
	'xml/node-observer.h',
	'xml/node.h',
	'xml/pi-node.h',
	'xml/quote-test.h',
	'xml/quote.h',
	'xml/rebase-hrefs.h',
	'xml/repr-action-test.h',
	'xml/repr-sorting.h',
	'xml/repr.h',
	'xml/simple-document.h',
	'xml/simple-node.h',
	'xml/sp-css-attr.h',
	'xml/subtree.h',
	'xml/text-node.h',
	'xml/href-attribute-helper.h'
]

lib_inkscape_src += xml_src
