path_src = [
  'path/path-boolop.cpp',
  'path/path-object-set.cpp',
  'path/path-offset.cpp',
  'path/path-outline.cpp',
  'path/path-simplify.cpp',
  'path/path-util.cpp',
  'path/splinefit/bezier-fit.cpp',
  'path/splinefit/splinefit.c',
  'path/splinefit/splinefont.c',
  'path/splinefit/splinerefigure.c',

  # -------
  # Headers
  'path/path-boolop.h',
  'path/path-offset.h',
  'path/path-outline.h',
  'path/path-simplify.h',
  'path/path-util.h',
  'path/splinefit/splinefit.h',
  'path/splinefit/splinefont.h'
]

lib_inkscape_src += path_src