svg_src = [
    'svg/css-ostringstream.cpp',
    'svg/path-string.cpp',
    # sp-svg.def
    'svg/stringstream.cpp',
    'svg/strip-trailing-zeros.cpp',
    'svg/svg-affine.cpp',
    'svg/svg-affine-parser.cpp',
    'svg/svg-box.cpp',
    'svg/svg-angle.cpp',
    'svg/svg-length.cpp',
    'svg/svg-bool.cpp',
    'svg/svg-path.cpp',
    # -------
    # Headers
    'svg/css-ostringstream.h',
    'svg/path-string.h',
    'svg/stringstream.h',
    'svg/strip-trailing-zeros.h',
    'svg/svg-box.h',
    'svg/svg-angle.h',
    'svg/svg-length.h',
    'svg/svg-bool.h',
    'svg/svg.h'
]

lib_inkscape_src += svg_src
