io_src = [
  'io/dir-util.cpp',
  'io/file.cpp',
  'io/file-export-cmd.cpp',
  'io/recent-files.cpp',
  'io/resource.cpp',
  'io/sandbox.cpp',
  'io/fix-broken-links.cpp',
  'io/query-file-info.cpp',
  'io/stream/bufferstream.cpp',
  'io/stream/gzipstream.cpp',
  'io/stream/inkscapestream.cpp',
  'io/stream/stringstream.cpp',
  'io/stream/uristream.cpp',
  'io/stream/xsltstream.cpp',
  'io/sys.cpp',

  # -------
  # Headers
  'io/dir-util.h',
  'io/file.h',
  'io/file-export-cmd.h',
  'io/recent-files.h',
  'io/resource.h',
  'io/sandbox.h',
  'io/fix-broken-links.h',
  'io/query-file-info.h',
  'io/stream/bufferstream.h',
  'io/stream/gzipstream.h',
  'io/stream/inkscapestream.h',
  'io/stream/stringstream.h',
  'io/stream/uristream.h',
  'io/stream/xsltstream.h',
  'io/sys.h'
]

lib_inkscape_src += io_src