lib_inkscape_src = [
  'alignment-snapper.cpp',
  'attribute-rel-css.cpp',
  'attribute-rel-svg.cpp',
  'attribute-rel-util.cpp',
  'attribute-sort-util.cpp',
  'attributes.cpp',
  'auto-save.cpp',
  'axis-manip.cpp',
  'composite-undo-stack-observer.cpp',
  'conditions.cpp',
  'conn-avoid-ref.cpp',
  'context-fns.cpp',
  'css-chemistry.cpp',
  'desktop-events.cpp',
  'desktop-style.cpp',
  'desktop.cpp',
  'distribution-snapper.cpp',
  'document-subset.cpp',
  'document-undo.cpp',
  'document-update.cpp',
  'document.cpp',
  'event-log.cpp',
  'file.cpp',
  'filter-chemistry.cpp',
  'filter-enums.cpp',
  'gc-anchored.cpp',
  'gradient-chemistry.cpp',
  'gradient-drag.cpp',
  'guide-snapper.cpp',
  'grid-snapper.cpp',
  'id-clash.cpp',
  'inkscape.cpp',
  'inkscape-version-info.cpp',
  'layer-manager.cpp',
  'line-geometry.cpp',
  'line-snapper.cpp',
  'media.cpp',
  'message-context.cpp',
  'message-stack.cpp',
  'mod360.cpp',
  'object-colors.cpp',
  'object-hierarchy.cpp',
  'object-snapper.cpp',
  'page-manager.cpp',
  'path-chemistry.cpp',
  'path-prefix.cpp',
  'perspective-line.cpp',
  'preferences.cpp',
  'print.cpp',
  'proj_pt.cpp',
  'pure-transform.cpp',
  'rdf.cpp',
  'rubberband.cpp',
  'selcue.cpp',
  'selection-chemistry.cpp',
  'selection-describer.cpp',
  'selection.cpp',
  'seltrans-handles.cpp',
  'seltrans.cpp',
  'snap-preferences.cpp',
  'snap.cpp',
  'snapped-curve.cpp',
  'snapped-line.cpp',
  'snapped-point.cpp',
  'snapper.cpp',
  'style-internal.cpp',
  'style.cpp',
  'text-chemistry.cpp',
  'text-editing.cpp',
  'transf_mat_3x4.cpp',
  'unicoderange.cpp',
  'vanishing-point.cpp',
  'version.cpp',

   # -------
   # Headers
  'alignment-snapper.h',
  'attribute-rel-css.h',
  'attribute-rel-svg.h',
  'attribute-rel-util.h',
  'attribute-sort-util.h',
  'attributes.h',
  'auto-save.h',
  'axis-manip.h',
  'bad-uri-exception.h',
  'composite-undo-stack-observer.h',
  'conditions.h',
  'conn-avoid-ref.h',
  'context-fns.h',
  'css-chemistry.h',
  'desktop-events.h',
  'desktop-style.h',
  'desktop.h',
  'distribution-snapper.h',
  'document-subset.h',
  'document-undo.h',
  'document-update.h',
  'document.h',
  'enums.h',
  'event-log.h',
  'event.h',
  'file.h',
  'fill-or-stroke.h',
  'filter-chemistry.h',
  'filter-enums.h',
  'gc-anchored.h',
  'gradient-chemistry.h',
  'gradient-drag.h',
  'guide-snapper.h',
  'grid-snapper.h',
  'id-clash.h',
  'inkscape-version.h',
  'inkscape-version-info.h',
  'inkscape.h',
  'layer-manager.h',
  'line-geometry.h',
  'line-snapper.h',
  'media.h',
  'message-context.h',
  'message-stack.h',
  'message.h',
  'mod360.h',
  'number-opt-number.h',
  'object-colors.h',
  'object-hierarchy.h',
  'object-snapper.h',
  'page-manager.h',
  'path-chemistry.h',
  'path-prefix.h',
  'pattern-manager.cpp',
  'pattern-manager.h',
  'pattern-manipulation.cpp',
  'pattern-manipulation.h',
  'perspective-line.h',
  'preferences-skeleton.h',
  'preferences.h',
  'print.h',
  'proj_pt.h',
  'pure-transform.h',
  'rdf.h',
  'rubberband.h',
  'selcue.h',
  'selection-chemistry.h',
  'selection-describer.h',
  'selection.h',
  'seltrans-handles.h',
  'seltrans.h',
  'snap-candidate.h',
  'snap-enums.h',
  'snap-preferences.h',
  'snap.h',
  'snapped-curve.h',
  'snapped-line.h',
  'snapped-point.h',
  'snapper.h',
  'streq.h',
  'strneq.h',
  'style-enums.h',
  'style-internal.h',
  'style.h',
  'syseq.h',
  'text-chemistry.h',
  'text-editing.h',
  'text-tag-attributes.h',
  'transf_mat_3x4.h',
  'undo-stack-observer.h',
  'unicoderange.h',
  'vanishing-point.h',
  'version.h',

  # TEMP  Need to detangle inkscape-view from ui/interface.cpp
  'inkscape-window.h',
  'inkscape-window.cpp',

  'inkscape-application.h',
  'inkscape-application.cpp',
  'actions/actions-effect-data.h',
  'actions/actions-effect-data.cpp',
  'actions/actions-extra-data.h',
  'actions/actions-extra-data.cpp',
  'actions/actions-hint-data.h',
  'actions/actions-hint-data.cpp',

  'actions/actions-base.h',
  'actions/actions-base.cpp',
  'actions/actions-canvas-mode.h',
  'actions/actions-canvas-mode.cpp',
  'actions/actions-canvas-snapping.h',
  'actions/actions-canvas-snapping.cpp',
  'actions/actions-canvas-transform.h',
  'actions/actions-canvas-transform.cpp',
  'actions/actions-dialogs.cpp',
  'actions/actions-dialogs.h',
  'actions/actions-edit-document.h',
  'actions/actions-edit-document.cpp',
  'actions/actions-edit-window.h',
  'actions/actions-edit-window.cpp',
  'actions/actions-edit.h',
  'actions/actions-edit.cpp',
  'actions/actions-effect.h',
  'actions/actions-effect.cpp',
  'actions/actions-element-a.h',
  'actions/actions-element-a.cpp',
  'actions/actions-element-image.h',
  'actions/actions-element-image.cpp',
  'actions/actions-file-window.h',
  'actions/actions-file-window.cpp',
  'actions/actions-file.h',
  'actions/actions-file.cpp',
  'actions/actions-helper.h',
  'actions/actions-helper.cpp',
  'actions/actions-helper-gui.h',
  'actions/actions-helper-gui.cpp',
  'actions/actions-help-url.h',
  'actions/actions-help-url.cpp',
  'actions/actions-hide-lock.h',
  'actions/actions-hide-lock.cpp',
  'actions/actions-layer.h',
  'actions/actions-layer.cpp',
  'actions/actions-node-align.h',
  'actions/actions-node-align.cpp',
  'actions/actions-object.h',
  'actions/actions-object.cpp',
  'actions/actions-object-align.h',
  'actions/actions-object-align.cpp',
  'actions/actions-output.h',
  'actions/actions-output.cpp',
  'actions/actions-paths.h',
  'actions/actions-paths.cpp',
  'actions/actions-selection-object.h',
  'actions/actions-selection-object.cpp',
  'actions/actions-selection-window.h',
  'actions/actions-selection-window.cpp',
  'actions/actions-selection.h',
  'actions/actions-selection.cpp',
  'actions/actions-text.h',
  'actions/actions-text.cpp',
  'actions/actions-tools.h',
  'actions/actions-tools.cpp',
  'actions/actions-tutorial.h',
  'actions/actions-tutorial.cpp',
  'actions/actions-transform.h',
  'actions/actions-transform.cpp',
  'actions/actions-undo-document.h',
  'actions/actions-undo-document.cpp',
  'actions/actions-view-mode.h',
  'actions/actions-view-mode.cpp',
  'actions/actions-view-window.h',
  'actions/actions-view-window.cpp',
  'actions/actions-window.h',
  'actions/actions-window.cpp',
  'actions/actions-pages.h',
  'actions/actions-pages.cpp',
  'actions/actions-svg-processing.h',
  'actions/actions-svg-processing.cpp',

  'inkview-application.h',
  'inkview-application.cpp',
  'inkview-window.h',
  'inkview-window.cpp',

  'manipulation/copy-resource.h',
  'manipulation/copy-resource.cpp'
]

subdir('actions')
subdir('async')
subdir('colors')
subdir('css')
subdir('debug')
subdir('display')
subdir('extension')
subdir('helper')
subdir('include')
subdir('io')
subdir('live_effects')
subdir('object')
subdir('path')
subdir('svg')
subdir('trace')
subdir('ui')
subdir('util')
subdir('util-string')
subdir('widgets')
subdir('xml')

subdir('inkgc')
subdir('livarot')
subdir('libnrtype')

###########################
# Import subprojects
###########################

cmake = import('cmake')

# Set CMake options
options = cmake.subproject_options()
# Do not build tests since they depend on GTest
options.add_cmake_defines({'2GEOM_TESTING': false},
                          {'2GEOM_BUILD_SHARED': true},
                          {'LIBCROCO_TESTING': false})

libcroco_subproject = cmake.subproject('libcroco', options: options)
message('- libcroco subproject available targets: ' + '\n + '.join(libcroco_subproject.target_list()) )
libcroco_dep = libcroco_subproject.target('croco_LIB')

wrapper_subproject = cmake.subproject('wrapper', options: options)
message('- wrapper subproject available targets: ' + '\n + '.join(wrapper_subproject.target_list()) )
geom_dep = wrapper_subproject.target('2geom')
libdepixelize_dep = wrapper_subproject.target('depixelize_LIB')




adaptagrams_subproject = cmake.subproject('adaptagrams')
libavoid_dep = adaptagrams_subproject.target('avoid_LIB')
libcola_dep = adaptagrams_subproject.target('cola_LIB')
libvpsc_dep = adaptagrams_subproject.target('vpsc_LIB')

autotrace_subproject = cmake.subproject('autotrace')
autotrace_dep = autotrace_subproject.target('autotrace_LIB')

#####################################

# Link with external dependencies
lib_inkscape_deps = []

# Link with libraries from our source code
lib_inkscape_link = [
    libcroco_dep,
    geom_dep,
    libavoid_dep,
    libcola_dep,
    libvpsc_dep,
    libdepixelize_dep,
    autotrace_dep    
]


lib_inkscape = shared_library('libinkscape',
    lib_inkscape_src,
    dependencies: lib_inkscape_deps,
    link_with: lib_inkscape_link
)

inkscape = executable('inkscape',
    'inkscape-main.cpp',
    link_with: lib_inkscape
)

inkview = executable('inkview',
    'inkview-main.cpp',
    link_with: lib_inkscape
)
