helper_src = [
	'helper/geom.cpp',
	'helper/geom-nodetype.cpp',
	'helper/geom-pathstroke.cpp',
	'helper/geom-pathvector_nodesatellites.cpp',
	'helper/geom-nodesatellite.cpp',
	'helper/gettext.cpp',
	'helper/pixbuf-ops.cpp',
	'helper/png-write.cpp',
	'helper/stock-items.cpp',
	#units-test.cpp

	# -------
	# Headers
	'helper/geom-curves.h',
	'helper/geom-nodetype.h',
	'helper/geom-pathstroke.h',
	'helper/geom-pathvector_nodesatellites.h',
	'helper/geom-nodesatellite.h',
	'helper/geom.h',
	'helper/gettext.h',
	'helper/mathfns.h',
	'helper/pixbuf-ops.h',
	'helper/png-write.h',
	'helper/stock-items.h'
]

lib_inkscape_src += helper_src